### ISSUE TITLE
Dead link in README

### ISSUE THREAD

**Issue by maxnth** [deutschestextarchiv/gt_structure_dtaText#1]
The link to [Arbeitsanweisung zur manuellen Erfassung von Texten im DTAsimple-Format für das Deutsche Textarchiv](https://kaskade.dwds.de/~matthias/DTA4doc/docu_transcription/Arbeitsanweisung_Texterfassung_20190710.pdf) leads to a 404 for me.

**Comment by tboenig** [comment]
Thank you.
